```python
"""Template system for code generation"""

import os
import re
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional, Callable
from dataclasses import dataclass
from string import Template

logger = logging.getLogger("orchestration.templates")


@dataclass
class TemplateContext:
    """Template rendering context"""
    class_name: str
    file_path: str
    fields: List[Dict[str, str]]
    methods: List[Dict[str, str]]
    imports: List[str]
    namespace: str = ""
    base_class: str = ""


class CodeTemplate:
    """Base code template"""
    
    name: str = ""
    extension: str = ""
    template: str = ""
    
    def render(self, context: TemplateContext) -> str:
        """Render template with context"""
        raise NotImplementedError


class HaskellTemplate(CodeTemplate):
    """Haskell template"""
    
    name = "haskell"
    extension = "hs"
    
    template = """-- Generated by AI Pipeline
-- Source: ${file_path}

module ${module_name} (${exports}) where

${imports}

${class_definition}
"""
    
    def render(self, context: TemplateContext) -> str:
        module_name = context.class_name.replace(".", "_").title().replace("_", "")
        
        template = Template(self.template)
        return template.safe_substitute(
            file_path=context.file_path,
            module_name=module_name,
            exports=", ".join([f.name for f in context.fields]) or "main",
            imports="\n".join(f"import {i}" for i in context.imports) or "-- No imports",
            class_definition=self._render_class(context),
        )
    
    def _render_class(self, context: TemplateContext) -> str:
        lines = []
        
        # Data type
        if context.fields:
            lines.append(f"data {context.class_name.replace('.', '_').title()} =")
            for i, field in enumerate(context.fields):
                suffix = " | " if i < len(context.fields) - 1 else ""
                lines.append(f"  {field['name']} :: {field['type']}{suffix}")
        
        # Functions
        if context.methods:
            lines.append("")
            for method in context.methods:
                lines.append(f"{method['name']} :: {method['type']}")
                lines.append(f"{method['name']} = undefined")
        
        return "\n".join(lines) or "-- Empty class"


class QMLTemplate(CodeTemplate):
    """QML template"""
    
    name = "qml"
    extension = "qml"
    
    template = """import QtQuick 2.15
import QtQuick.Controls 2.15

${base_type} {
${properties}
${signals}
${handlers}
}
"""
    
    def render(self, context: TemplateContext) -> str:
        base_type = context.base_class or "Item"
        
        template = Template(self.template)
        return template.safe_substitute(
            base_type=base_type,
            properties=self._render_properties(context),
            signals=self._render_signals(context),
            handlers=self._render_handlers(context),
        )
    
    def _render_properties(self, context: TemplateContext) -> str:
        lines = []
        for field in context.fields[:10]:
            qml_type = self._map_qml_type(field.get("type", "string"))
            lines.append(f"    property {qml_type} {field['name']}: {field.get('default', '\"\"')}")
        return "\n".join(lines) or "    // No properties"
    
    def _render_signals(self, context: TemplateContext) -> str:
        return "    signal clicked()"
    
    def _render_handlers(self, context: TemplateContext) -> str:
        return "    onClicked: { console.log('Clicked') }"
    
    def _map_qml_type(self, cpp_type: str) -> str:
        mapping = {
            "int": "int",
            "string": "string",
            "bool": "bool",
            "double": "real",
            "float": "real",
        }
        return mapping.get(cpp_type.lower(), "var")


class SQLTemplate(CodeTemplate):
    """SQL template"""
    
    name = "sql"
    extension = "sql"
    
    template = """-- Generated by AI Pipeline
-- Source: ${file_path}

CREATE TABLE ${table_name} (
${columns}
${primary_key}
${foreign_keys}
);

${indexes}
"""
    
    def render(self, context: TemplateContext) -> str:
        table_name = context.class_name.replace(".", "_").lower()
        
        template = Template(self.template)
        return template.safe_substitute(
            file_path=context.file_path,
            table_name=table_name,
            columns=self._render_columns(context),
            primary_key=self._render_primary_key(context),
            foreign_keys=self._render_foreign_keys(context),
            indexes=self._render_indexes(context),
        )
    
    def _render_columns(self, context: TemplateContext) -> str:
        lines = []
        for field in context.fields:
            sql_type = self._map_sql_type(field.get("type", "string"))
            nullable = "" if field.get("required") else " NULL"
            lines.append(f"    {field['name']} {sql_type}{nullable},")
        return "\n".join(lines)[:-1]  # Remove last comma
    
    def _render_primary_key(self, context: TemplateContext) -> str:
        pk_fields = [f["name"] for f in context.fields if f.get("primary_key")]
        if pk_fields:
            return f"    PRIMARY KEY ({', '.join(pk_fields)})"
        return ""
    
    def _render_foreign_keys(self, context: TemplateContext) -> str:
        return ""
    
    def _render_indexes(self, context: TemplateContext) -> str:
        return "-- No indexes"
    
    def _map_sql_type(self, cpp_type: str) -> str:
        mapping = {
            "int": "INTEGER",
            "long": "BIGINT",
            "string": "VARCHAR(255)",
            "bool": "BOOLEAN",
            "double": "DOUBLE PRECISION",
            "float": "REAL",
            "date": "DATE",
            "datetime": "TIMESTAMP",
        }
        return mapping.get(cpp_type.lower(), "TEXT")


class JasperTemplate(CodeTemplate):
    """JasperReports template"""
    
    name = "jasper"
    extension = "jrxml"
    
    template = """<?xml version="1.0"?>
<jasperReport name="${report_name}" pageWidth="595" pageHeight="842">
    <title>
        <band height="50">
            <staticText>
                <reportElement x="0" y="0" width="595" height="50"/>
                <text><![CDATA[${report_name}]]></text>
            </staticText>
        </band>
    </title>
    <detail>
        <band height="20">
${fields}
        </band>
    </detail>
</jasperReport>
"""
    
    def render(self, context: TemplateContext) -> str:
        template = Template(self.template)
        return template.safe_substitute(
            report_name=context.class_name,
            fields=self._render_fields(context),
        )
    
    def _render_fields(self, context: TemplateContext) -> str:
        lines = []
        for field in context.fields[:10]:
            lines.append(f'            <textField><reportElement x="{field.get("x", 0)}" y="0" width="100" height="20"/><textFieldExpression><![CDATA[$F{{{field['name']}}}]]></textFieldExpression></textField>')
        return "\n".join(lines) or "            <!-- No fields -->"


class TemplateEngine:
    """Template rendering engine"""
    
    def __init__(self):
        self.templates: Dict[str, CodeTemplate] = {
            "haskell": HaskellTemplate(),
            "qml": QMLTemplate(),
            "sql": SQLTemplate(),
            "jasper": JasperTemplate(),
        }
    
    def register_template(self, template: CodeTemplate):
        """Register custom template"""
        self.templates[template.name] = template
    
    def get_template(self, name: str) -> Optional[CodeTemplate]:
        """Get template by name"""
        return self.templates.get(name)
    
    def render(
        self,
        template_name: str,
        class_name: str,
        file_path: str,
        fields: List[Dict] = None,
        methods: List[Dict] = None,
        **kwargs,
    ) -> str:
        """Render template"""
        template = self.templates.get(template_name)
        if not template:
            raise ValueError(f"Unknown template: {template_name}")
        
        context = TemplateContext(
            class_name=class_name,
            file_path=file_path,
            fields=fields or [],
            methods=methods or [],
            imports=kwargs.get("imports", []),
            namespace=kwargs.get("namespace", ""),
            base_class=kwargs.get("base_class", ""),
        )
        
        return template.render(context)


# Global template engine
_engine: Optional[TemplateEngine] = None


def get_template_engine() -> TemplateEngine:
    """Get global template engine"""
    global _engine
    if _engine is None:
        _engine = TemplateEngine()
    return _engine
